param(
  [String[]]$StartIP,
  [Int]$ScanRange
)

# pingRange_v5.ps1 - by Kevin Birk, 12/17/25
# Scan a range of IPs with a simple ping scan to check if hosts are online
# This script scans up to 1024 consecutive hosts.

# sample usage: ./pingRange_v5.ps1 -StartIP <ipAddress> -ScanRange <int 1-1024>
# Output both in console and in a log file

#Check if an argument is a valid IP address
# A helper function generated by AI, edited for simplicity
# This regex check would have been very difficult for me to program otherwise...
function Test-IPv4Address {
  param (
      [string]$Address
  )

  # Strict IPv4 regex: matches 0-255 in each octet
  $ipv4Pattern = '^(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.' +
                  '(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.' +
                  '(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.' +
                  '(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)$'

  if ($Address -notmatch $ipv4Pattern) {
    Return 1
  }
  Return 0
}

# Check if the input is a real IP address; if not, fail out
if (Test-IPv4Address -Address $StartIP) {
  Write-Output "The ip address input is not a valid ip address."
  Exit 1
}

# Check if the scan range is 1024 or less
if (($ScanRange -lt 1) -or ($ScanRange -ge 1025)) {
  "Invalid scan range. Choose a range between 1 and 1024"
  Exit 1
}

# Define log path and create log file if it doesn't already exist
$LogFile = "pingRange_v5_($(Get-Date -Format "MMddyyHHmm")).txt"

# Write initial output to log (help to debug transforms below placing it here...)
Write-Output "Start IP Range Scan at $($DateTime)"
Add-Content -Path $LogFile -Value "Start IP Range Scan at $($DateTime)"
Write-Output "Starting address is $($StartIP)"
Add-Content -Path $LogFile -Value "Starting address is $($StartIP)"
Write-Output "Scan range is $($ScanRange)"
Add-Content -Path $LogFile -Value "Scan range is $($ScanRange)"

# Set starting IP address
$TargetIP = $StartIP

# Split IP address into separate octets
$TargetIPOctets = $TargetIP -split '\.'
$FirstOctet = [int]$TargetIPOctets[0]
$SecondOctet = [int]$TargetIPOctets[1]
$ThirdOctet = [int]$TargetIPOctets[2]
$FourthOctet = [int]$TargetIPOctets[3]

# Set local variable range to be scanned
$RangeRemaining = $ScanRange

# encase whole function in a while so can break from it as needed?
while ($RangeRemaining -ne 0) {
  # Do work
  $Result = Get-CimInstance -ClassName Win32_PingStatus -Filter "Address='$($TargetIP)' AND Timeout=1000"
  if ($Result.StatusCode -ne 0) {
    Write-Output "Host at $($TargetIP) is UNRESPONSIVE with status code $($Result.StatusCode)"
    Add-Content -Path $LogFile -Value "Host at $($TargetIP) is UNRESPONSIVE with status code $($Result.StatusCode)"
  } else {
    Write-Output "Host at $($TargetIP) is ONLINE"
    Add-Content -Path $LogFile -Value "Host at $($TargetIP) is ONLINE"
  }

  # Decrement scan range counter
  $RangeRemaining = $RangeRemaining - 1

  # Increment IP address
  if ($FourthOctet -eq 255) {
    if ($ThirdOctet -eq 255) {
      if ($SecondOctet -eq 255) {
        if ($FirstOctet -eq 255) {
          Write-Output "Max IP value exceeded! Breaking from loop!"
          Add-Content -Path $LogFile -Value "Max IP value exceeded! Breaking from loop!"
          break
        } else {
          $FirstOctet = $FirstOctet + 1
          $SecondOctet = 0
          $ThirdOctet = 0
          $FourthOctet = 0
        }
      } else {
        $SecondOctet = $SecondOctet + 1
        $ThirdOctet = 0
        $FourthOctet = 0
      }
    } else {
      $ThirdOctet = $ThirdOctet + 1
      $FourthOctet = 0
    }
  } else {
    $FourthOctet = $FourthOctet + 1
  }

  $TargetIP = (([string]$FirstOctet) + '.' + ([string]$SecondOctet) + '.' + ([string]$ThirdOctet) + '.' + ([string]$FourthOctet))

}

# Write final output and comments here to close out even if job breaks mid-loop
Write-Output "Scan job finished at $(Get-Date -Format "MMddyyHHmm")"
Add-Content -Path $LogFile -Value "Scan job finished at $(Get-Date -Format "MMddyyHHmm")"
Exit 0